# global
url: https://discord.true.nl
title: True Discord
github: https://github.com/true/discord-landing-page

# env specific
api_url: https://discord.com/api/guilds/420245177421004821/widget.json
vue_url: https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.min.js

# build
sass:
  style: compressed

exclude: [".scss", "README.md", "docker-compose.yml", "node_modules", "gruntfile.js", "package.json", "Gemfile", "Gemfile.lock", "LICENSE", "CNAME"]
